version: '3'

services:
  web:
    image: rentdoor
    container_name: rentdoor_webserver
    command: ["gunicorn", "--bind", "0.0.0.0:8000", "rentdoor.wsgi"]
    expose:
      - 8000
    environment:
      - APP_PORT=1234
      - DJANGO_SETTINGS_MODULE=settings.local
    links:
      - mysql
  mysql:
    image: mysql:8.0
    container_name: mysql_rentdoor
    restart: always
    ports:
      - "3315:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./setup/scripts:/docker-entrypoint-initdb.d
      - ./mysql_data_container:/var/lib/mysql:rw
    user: mysql
  phpmyadmin:
     image: phpmyadmin/phpmyadmin:latest
     container_name: phpmyadmin_rentdoor
     restart: always
     environment:
       - MYSQL_ROOT_PASSWORD=root
       - PMA_USER=root
       - PMA_PASSWORD=root
     ports:
       - "8092:80"
     links:
       - mysql:db
     depends_on:
       - mysql
  redis:
    image: redis:6.0
    container_name: redis_rentdoor
    restart: always
    ports:
      - "6379:6379"
  nginx:
    build: ./setup/nginx
    container_name: nginx_rentdoor
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  db:
