version: '3'

services:
  web:
    image: rentdoor
    container_name: rentdoor_webserver
    cap_add:
      - SYS_PTRACE
    expose:
      - 8000
    env_file:
      - .env
    volumes:
      - .:/reviews
    links:
      - mysql
  mysql:
    image: mysql:8.0
    container_name: mysql_rentdoor
    restart: always
    ports:
      - "3315:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./setup/mysql:/docker-entrypoint-initdb.d
      - ./mysql_data_container:/var/lib/mysql:rw
    user: mysql
  phpmyadmin:
     image: phpmyadmin/phpmyadmin:latest
     container_name: phpmyadmin_rentdoor
     restart: always
     environment:
       - MYSQL_ROOT_PASSWORD=root
       - PMA_USER=root
       - PMA_PASSWORD=root
     ports:
       - "8092:80"
     links:
       - mysql:db
     depends_on:
       - mysql
  redis:
    image: redis:6.0
    container_name: redis_rentdoor
    restart: always
    ports:
      - "6379:6379"
  nginx:
    build:
      context: ./setup/nginx
      args:
        - ENV=$ENV
    container_name: nginx_rentdoor
    volumes:
      - ./staticfiles:/staticfiles/
      - ./media:/media/
      - ./certbot/www/:/var/www/certbot/:ro
      - ./certbot:/certbot/
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

volumes:
  db:
